# Generated by Django 2.2.1 on 2019-05-17 16:58

import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0001_aaaa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('service', models.CharField(choices=[('AS', 'Google AdSense'), ('KC', 'KeyCDN'), ('RN', 'RamNode'), ('DN', 'DNSMadeEasy')], default='AS', max_length=2)),
                ('extra_data', django.contrib.postgres.fields.hstore.HStoreField()),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
