# Generated by Django 2.2.1 on 2019-05-17 17:07

import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_auto_20190517_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsetask',
            name='extra_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=list),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='login',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
